version: '3'

services:
  proxy:
    image: nginx:1.13 # menggunakan image versi 1.13.x
    ports:
      - '80:80' # expose port 80 host ke 80 container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    image: httpd  # menggunakan image httpd:latest
